theme: minima
title: Devin Lane Jekyll experiment blog
author: Devin Lane
email: experiment at cool dot com
description: > # this means to ignore newlines until "baseurl:"
  A blog experiment.

# social links
twitter_username: devinclane # DO NOT include the @ character, or else the build will fail!
github_username:  devinclane # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
